- name: Configure Nginx for app
  hosts: all
  remote_user: deploy
  roles:
    - role: app

- name: Add Rails app database and user
  hosts: all
  remote_user: deploy
  roles:
    - role: rails_db

- name: Upload DB
  hosts: all
  remote_user: deploy
  roles:
    - role: upload_db
