- name: Configure Nginx for app
  hosts: rails
  remote_user: deploy
  roles:
    - role: app

- name: Add Rails app database and user
  hosts: rails
  remote_user: deploy
  roles:
    - role: rails_db

- name: Upload DB
  hosts: rails
  remote_user: deploy
  roles:
    - role: upload_db

- name: Automate backups
  hosts: rails
  remote_user: deploy
  roles:
    - { role: backups, when: (backup_to_aws is defined) and backup_to_aws }
