---
# Add deploy user, ssh key, setup ohmyzsh and install nginx with middleman.dev default host.

- name: Setup user
  hosts: all
  remote_user: root
  roles:
    - { role: users }
    - { role: manala.git }
    - { role: manala.zsh }
    - { role: mashimom.oh-my-zsh, ohmyzsh_theme: 'aussiegeek' }

- name: Setup user environment
  hosts: all
  remote_user: deploy
  roles:
    - { role: mashimom.oh-my-zsh, ohmyzsh_theme: 'aussiegeek' }

- name: Install all necessary software
  hosts: all
  remote_user: deploy
  become: yes
  roles:
    - { role: common }

- name: Setup monit
  hosts: all
  remote_user: root
  roles:
    - { role: pgolm.monit }
    - { role: setup_monit }

- name: Setup nginx and passenger
  hosts: all
  remote_user: deploy
  become: yes
  vars:
    default_host: middleman.dev
    passenger_root: /usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini
    passenger_ruby: /usr/local/rvm/gems/ruby-{{ ruby_version }}/wrappers/ruby
    passenger_app_env: production
    passenger_app_root: /home/deploy/var/www/{{ app_name }}/current/public
    passenger_server_name: "{{ app_name }}.dev"
  roles:
    - { role: geerlingguy.passenger }
    - { role: nginx }
    # - { role: passenger }

- name: Install redis
  hosts: all
  remote_user: deploy
  become: yes
  vars:
    - redis_bind: 127.0.0.1
    - redis_version: 3.2.3
  roles:
    - { role: DavidWittman.redis }

- name: Install Ruby
  hosts: all
  remote_user: deploy
  roles:
    - role: rvm_io.rvm1-ruby
      become: yes
      rvm1_rubies:
        - 'ruby-{{ ruby_version }}'
    - role: ruby

- name: Install PostgreSQL
  hosts: all
  remote_user: deploy
  become: yes
  roles:
    - role: ANXS.PostgreSQL
      postgresql_version: 9.5
      postgresql_encoding: 'UTF-8'
      postgresql_locale: 'en_US.UTF-8'

      postgresql_admin_user: 'postgres'
      postgresql_default_auth_method: 'trust'

